kind: pipeline
type: exec
name: build & deploy

steps:
- name: build
  commands:
  - docker build --pull --rm -t flaskdronebootstrap:latest . 
- name: deploy
  commands:
  - docker stop flaskdronebootstrap || true && docker rm flaskdronebootstrap || true
  - docker run -p 5000:5000 --name flaskdronebootstrap -d --network="host"  flaskdronebootstrap:latest .